Use `search_list_with_dicts` from the op.api package
openprocurement/openprocurement.caravan pull request #14
Opened 2019-02-06 07:50 UTC by bdmbdsm

2019-02-06 09:32 UTC, vmotso approved these changes

2019-02-06 10:56 UTC, Scandie commented
@bdmbdsm, Функція використовується ще [тут](https://github.com/openprocurement/openprocurement.caravan/blob/ef2d4027c2a6795d3b65b949150a5c1e92e43a12/openprocurement/caravan/utils.py#L98), потрібно додати імпорт.

2019-02-06 10:57 UTC, Scandie requested changes
@bdmbdsm, Функція використовується ще [тут](https://github.com/openprocurement/openprocurement.caravan/blob/ef2d4027c2a6795d3b65b949150a5c1e92e43a12/openprocurement/caravan/utils.py#L98), потрібно додати імпорт.

2019-02-07 08:43 UTC, bdmbdsm commented
@Scandie 
вніс відповідні зміни :memo:

2019-02-07 09:25 UTC, Scandie approved these changes

2024-09-18 07:11 UTC, closed without merging